package AutoLegacyTest::Lists;

require Exporter;
@ISA = qw(Exporter);
@EXPORT = qw(Whitelist Blacklist);

sub Whitelist {
  return
    {
    };
}

sub BlacklistOrig {
  return
    {
     'main::AutoLegacyTest' => 1,
     'main::AutoLegacyTest::Lists' => 1,
     'main::Sayer2' => 1,

     'main::AutoLegacyTest::Dumper' => 1,

     'main::Data::Dumper' => 1,
     'main::Hook::PrePostCall' => 1,
     'main::Symbol::Table' => 1,

     'main::re' => 1,
     'main::Regexp' => 1,
    };
}

sub Blacklist {
  return
    {
     # 'main::parent' => 1,
     # 'main::integer' => 1,
     # # 'main::Algorithm::Diff' => 1,
     # # 'main::Time::HiRes' => 1,
     # 'main::File::Temp' => 1,
     # 'main::PerlLib::Cacher' => 1,
     # # 'main::PerlLib::IE::AIE' => 1,
     # 'main::PerlLib::RSSReader' => 1,
     # 'main::PerlLib::SwissArmyKnife' => 1,
     # 'main::PerlLib::ToText::StrangeCharacters' => 1,
     # 'main::Sub::Quote' => 1,
     # 'main::Moo::sification' => 1,
     # 'main::Module::Runtime' => 1,


     'AutoLegacyTest::__ANON__' => 1,

     'main::DBD::mysql::db' => 1,
     'main::DBD::mysql::st' => 1,
     'main::AutoLegacyTest' => 1,
     'main::AutoLegacyTest::Lists' => 1,
     'main::Sayer2' => 1,
     'main::Sayer2::DBDHash' => 1,
     'main::Sayer2::Dumper' => 1,
     'main::Sayer2::Util' => 1,
     'main::Sayer2::MySQL' => 1,
     'main::Sayer2::Dialog' => 1,
     'main::Sayer2::Streamer' => 1,

     'main::Sayer' => 1,
     'main::Sayer::DBDHash' => 1,
     'main::Sayer::Dumper' => 1,
     'main::Sayer::Util' => 1,
     'main::Sayer::MySQL' => 1,
     'main::Sayer::Dialog' => 1,
     'main::Sayer::Streamer' => 1,

     'main::AutoLegacyTest::Dumper' => 1,

     'main::Data::Dumper' => 1,
     'main::Data::Dumper::Streamer' => 1,
     'main::Hook::PrePostCall' => 1,
     'main::Symbol::Table' => 1,

     'main::re' => 1,
     'main::Regexp' => 1,

     'main::arybase' => 1,
     'main::arybase::mg' => 1,
     'main::AutoLoader' => 1,
     'main::B' => 1,
     'main::base' => 1,
     'main::B::AV' => 1,
     'main::B::BINOP' => 1,
     'main::B::BM' => 1,
     'main::B::COP' => 1,
     'main::B::CV' => 1,
     'main::B::Deparse' => 1,
     'main::B::Deparse::coderef2text' => 1,
     'main::B::FM' => 1,
     'main::B::GV' => 1,
     'main::B::HE' => 1,
     'main::B::HV' => 1,
     'main::B::IO' => 1,
     'main::B::IV' => 1,
     'main::B::LISTOP' => 1,
     'main::B::LOGOP' => 1,
     'main::B::LOOP' => 1,
     'main::B::MAGIC' => 1,
     'main::B::METHOP' => 1,
     'main::B::NULL' => 1,
     'main::B::NV' => 1,
     'main::B::OP' => 1,
     'main::B::PADLIST' => 1,
     'main::B::PADNAME' => 1,
     'main::B::PADNAMELIST' => 1,
     'main::B::PADOP' => 1,
     'main::B::PMOP' => 1,
     'main::B::PV' => 1,
     'main::B::PVLV' => 1,
     'main::B::PVMG' => 1,
     'main::B::PVOP' => 1,
     'main::B::REGEXP' => 1,
     'main::B::RHE' => 1,
     'main::B::SV' => 1,
     'main::B::SVOP' => 1,
     'main::B::UNOP' => 1,
     'main::B::UNOP_AUX' => 1,
     'main::B::Utils' => 1,
     'main::bytes' => 1,
     'main::Carp' => 1,
     'main::Class::MethodMaker' => 1,
     'main::Class::MethodMaker::Engine' => 1,
     'main::Class::MethodMaker::OptExt' => 1,
     'main::Class::MethodMaker::scalar' => 1,
     'main::Class::MethodMaker::V1Compat' => 1,
     'main::Config' => 1,
     'main::constant' => 1,
     'main::Cwd' => 1,
     'main::Data::Dump::Streamer' => 1,
     'main::Data::Dump::Streamer::Out' => 1,
     'main::Data::Dump::Streamer::_dump_sv' => 1,
     'main::Data::Dump::Streamer::_dump_rv' => 1,
     'main::Data::Dump::Streamer::_dump_code' => 1,
     'main::Data::Dump::Streamer::Deparser' => 1,
     'main::DBD::Switch::dr' => 1,
     'main::DBI' => 1,
     'main::DBI::common' => 1,
     'main::DBI::db' => 1,
     'main::DBI::dr' => 1,
     'main::DBI::st' => 1,
     'main::DBI::var' => 1,
     'main::DynaLoader' => 1,
     'main::Encode' => 1,
     'main::Encode::Alias' => 1,
     'main::Encode::Encoding' => 1,
     'main::Encode::Internal' => 1,
     'main::Encode::utf8' => 1,
     'main::Encode::XS' => 1,
     'main::Errno' => 1,
     'main::Error' => 1,
     'main::Error::Simple' => 1,
     'main::Error::subs' => 1,
     'main::Error::WarnDie' => 1,
     'main::Exporter' => 1,
     'main::Exporter::Heavy' => 1,
     'main::Fcntl' => 1,
     'main::feature' => 1,
     'main::File::Basename' => 1,
     'main::File::Find' => 1,
     'main::File::Slurp' => 1,
     'main::File::Spec::Unix' => 1,
     'main::File::Stat' => 1,
     'main::Hash::Util' => 1,
     'main::Internals' => 1,
     'main::IO' => 1,
     'main::IO::File' => 1,
     'main::IO::Handle' => 1,
     'main::IO::Poll' => 1,
     'main::IO::Seekable' => 1,
     'main::IO::Socket' => 1,
     'main::List::Util' => 1,
     'main::Manager::Dialog' => 1,
     'main::mro' => 1,
     'main::overload' => 1,
     'main::overloading' => 1,
     'main::PadWalker' => 1,
     'main::PerlIO' => 1,
     'main::PerlIO::Layer' => 1,
     'main::PerlLib::MySQL' => 1,
     'main::PerlLib::Util' => 1,
     'main::POSIX' => 1,
     'main::POSIX::SigAction' => 1,
     'main::POSIX::SigRt' => 1,
     'main::POSIX::SigSet' => 1,
     'main::POSIX::Termios' => 1,
     'main::Proc::ProcessTable' => 1,
     'main::Proc::ProcessTable::Process' => 1,
     'main::Scalar::Util' => 1,
     'main::SelectSaver' => 1,
     'main::SelfLoader' => 1,
     'main::strict' => 1,
     'main::String::Similarity' => 1,
     'main::subs' => 1,
     'main::Sub::Util' => 1,
     'main::Symbol' => 1,
     'main::Term::ReadKey' => 1,
     'main::Text::Abbrev' => 1,
     'main::Text::Balanced' => 1,
     'main::Text::Balanced::Extractor' => 1,
     'main::Text::Tabs' => 1,
     'main::Text::Wrap' => 1,
     'main::Tie::ExtraHash' => 1,
     'main::Tie::Hash' => 1,
     'main::Tie::StdHash' => 1,
     'main::Tk' => 1,
     'main::Tk::After' => 1,
     'main::Tk::After::Cancelled' => 1,
     'main::Tk::Button' => 1,
     'main::Tk::Callback' => 1,
     'main::Tk::Checkbutton' => 1,
     'main::Tk::CmdLine' => 1,
     'main::Tk::Configure' => 1,
     'main::Tk::Derived' => 1,
     'main::Tk::Dialog' => 1,
     'main::Tk::DialogBox' => 1,
     'main::Tk::Event' => 1,
     'main::Tk::Event::IO' => 1,
     'main::Tk::Event::Source' => 1,
     'main::Tk::Font' => 1,
     'main::Tk::FontRankInfo' => 1,
     'main::Tk::Frame' => 1,
     'main::Tk::Image' => 1,
     'main::Tk::MainWindow' => 1,
     'main::Tk::Submethods' => 1,
     'main::Tk::Toplevel' => 1,
     'main::Tk::Widget' => 1,
     'main::Tk::Wm' => 1,
     'main::Tk::Xrm' => 1,
     'main::Try::Tiny' => 1,
     'main::UNIVERSAL' => 1,
     'main::utf8' => 1,
     'main::vars' => 1,
     'main::version' => 1,
     'main::warnings' => 1,
     'main::warnings::register' => 1,
     'main::XEvent' => 1,
     'main::XSLoader' => 1,
    };
}
